services:
  mongo:
    image: mongo:latest
    container_name: stockflow-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - stockflow-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: stockflow-user-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/stockflow
      - JWT_SECRET=stockflow_user_service_jwt_secret_key_2026
    depends_on:
      - mongo
    networks:
      - stockflow-network

volumes:
  mongo_data:

networks:
  stockflow-network:
    driver: bridge
